878 Update Mock server for FAPs
UserOfficeProject/mock-uows pull request #11
Opened 2023-12-11 17:07 UTC by TCMeldrum

Part of: https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/878

## Description

Updates Mockserver to give FAP roles to some users and adds more users for some methods. 

## Motivation and Context

Have the FAPs test suite work in STFC mode

## How Has This Been Tested
https://github.com/UserOfficeProject/user-office-core/actions/runs/7170305690
## Fixes

## Changes

## Depends on

## Tests included/Docs Updated?

- [ ] I have added tests to cover my changes.
- [ ] All relevant doc has been updated

2023-12-14 09:16 UTC, ellen-wright requested changes

2023-12-14 09:16 UTC, ellen-wright commented on src/responses/user/notEmptyResponse.xml
> +<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><ns2:getBasicPeopleDetailsFromUserNumbersResponse xmlns:ns2="http://webservice.UserOffice.stfc.com/"><return><country>
```suggestion
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><ns2:getBasicPeopleDetailsFromUserNumbersResponse xmlns:ns2="http://webservice.UserOffice.stfc.com/"><return><country>UNITED KINGDOM</country><deptName>ISIS</deptName><displayName>Benjamin Beckley</displayName><email>ben@inbox.com</email><establishmentId>7</establishmentId><familyName>Beckley</familyName><firstNameKnownAs>Ben</firstNameKnownAs><fullName>Mr Benjamin Beckley</fullName><givenName>Benjamin</givenName><initials>B</initials><orgName>STFC</orgName><title>Mr</title><userNumber>4</userNumber></return><return><country>UNITED KINGDOM</country><deptName>ISIS</deptName><displayName>Unverified email Placeholder</displayName><email>unverified-user@example.com</email><establishmentId>7</establishmentId><familyName>Placeholder</familyName><firstNameKnownAs>Unverified email</firstNameKnownAs><fullName>Mr Unverified email Placeholder</fullName><givenName>Unverified email</givenName><initials>U</initials><orgName>STFC</orgName><title>Mr</title><userNumber>5</userNumber></return><return><country>UNITED KINGDOM</country><deptAcronym>SCD</deptAcronym><deptName>Scientific Computing</deptName><displayName>Carl Carlsson</displayName><email>Javon4@hotmail.com</email><establishmentId>5</establishmentId><familyName>Carlsson</familyName><firstNameKnownAs>Carl</firstNameKnownAs><fullName>Mr Carl Carlsson</fullName><givenName>Carl</givenName><initials>C</initials><orgName>STFC</orgName><title>Miss</title><userNumber>0</userNumber></return><return><country>UNITED KINGDOM</country><deptAcronym>SCD</deptAcronym><deptName>Scientific Computing</deptName><displayName>Carl Carlsson</displayName><email>Javon4@hotmail.com</email><establishmentId>5</establishmentId><familyName>Carlsson</familyName><firstNameKnownAs></firstNameKnownAs><fullName>Mr Carl Carlsson</fullName><givenName>Carl</givenName><initials>C</initials><orgName>STFC</orgName><title>Miss</title><userNumber>1</userNumber></return><return><country>UNITED KINGDOM</country><deptName>ISIS</deptName><displayName>test 3</displayName><email>unverified-user@example.com</email><establishmentId>7</establishmentId><familyName>Placeholder</familyName><firstNameKnownAs>Unverified email</firstNameKnownAs><fullName>Mr Unverified email Placeholder</fullName><givenName>Unverified email</givenName><initials>U</initials><orgName>STFC</orgName><title>Mr</title><userNumber>2</userNumber></return><return><country>UNITED KINGDOM</country><deptAcronym>SCD</deptAcronym><deptName>Scientific Computing</deptName><displayName>Nils</displayName><email>nils@ess.se</email><establishmentId>5</establishmentId><familyName>Nilsson</familyName><firstNameKnownAs>Nils</firstNameKnownAs><fullName>Mr Nils Nilsson</fullName><givenName>Nils</givenName><initials>N</initials><orgName>STFC</orgName><title>Mr</title><userNumber>3</userNumber></return><return><country>UNITED KINGDOM</country><deptAcronym>SCD</deptAcronym><deptName>Scientific Computing</deptName><displayName>David Dawson</displayName><email>david@teleworm.us</email><establishmentId>5</establishmentId><familyName>Dawson</familyName><fedId>abc12345</fedId><firstNameKnownAs>David</firstNameKnownAs><fullName>Mr David Dawson</fullName><givenName>David</givenName><initials>DD</initials><mobilePhone>08579366828</mobilePhone><orgName>STFC</orgName><status>Undergraduate Student</status><title>Mr</title><userNumber>6</userNumber></return></ns2:getBasicPeopleDetailsFromUserNumbersResponse></soap:Body></soap:Envelope>
```

I think we should keep the firstNameKnownAs for user 4 as Ben and remove it for user 1 to match the other files

2023-12-14 11:29 UTC, ellen-wright approved these changes

2023-12-15 10:19 UTC, ACLay approved these changes
I'm not sure I follow what the roleMappings object does, but the changes to it seem consistent with how it was before, so I think this should be okay

2023-12-15 10:58 UTC, merged